ci: Install using either dnf or microdnf

diff --git a/.github/workflows/molecule_dev_tools.yml b/.github/workflows/molecule_dev_tools.yml
--- a/.github/workflows/molecule_dev_tools.yml
+++ b/.github/workflows/molecule_dev_tools.yml
@@ -100,7 +100,13 @@ jobs:
       - name: 'Install podman'
         if: 'matrix.container.install_podman'
         run: |
-          dnf install podman -y
+          if command -v dnf; then
+            dnf install podman -y
+          elif command -v microdnf; then
+            microdnf install podman -y
+          else
+            echo "ERROR: Neither dnf nor microdnf found!"
+            exit 1
 
       - name: 'Run molecule'
         run: |
